### ISSUE TITLE
How to produce "RepeatMaskerUnique" File?

### ISSUE THREAD

**Issue by Bathroomboss** [AssumeAssume/Li_et_al_2024#1]
Dear Dr Li:

Hi, thank you so much for sharing your code.

I would like to replicate the analysis of my own RNA-seq data following your method. But I am not quite clear on the specific meaning of **RepeatMaskerUnique** and how it is generated in your **RNA-seq_pipeline.sh**. Could you please briefly describe it for me?

Best,
Yu

**Comment by AssumeAssume** [comment]
Hi Yu,
Thanks for your interest!
Briefly, we first download the repeatmasker file in the `UCSC table browser`, typically the file looks like 
`cat rmsk.txt|head -n 5`
| Column1 | Column2 | Column3 | Column4 | Column5 | Chromosome | Start   | End     | Position     | Strand | Subfamily       | Class        | Family       | Col14 | Col15 | Col16 | ID |
|---------|---------|---------|---------|---------|------------|---------|---------|--------------|--------|------------|--------------|--------------|-------|-------|-------|----|
| 585     | 463     | 13      | 6       | 17      | chr1       | 10000   | 10468   | -248945954   | +      | (TAACCC)n  | Simple_repeat | Simple_repeat | 1     | 471   | 0     | 1  |
| 585     | 3612    | 114     | 215     | 13      | chr1       | 10468   | 11447   | -248944975   | -      | TAR1       | Satellite    | telo         | -399  | 1712  | 483   | 2  |
| 585     | 484     | 251     | 132     | 0       | chr1       | 11504   | 11675   | -248944747   | -      | L1MC5a     | LINE         | L1           | -2382 | 395   | 199   | 3  |
| 585     | 239     | 294     | 19      | 10      | chr1       | 11677   | 11780   | -248944642   | -      | MER5B      | DNA          | hAT-Charlie  | -74   | 104   | 1     | 4  |
| 585     | 318     | 230     | 37      | 0       | chr1       | 15264   | 15355   | -248941067   | -      | MIR3       | SINE         | MIR          | -119  | 143   | 49    | 5  |

Next we convert this file into gtf format, used for `featureCounts`
`cat rmsk.txt|awk 'BEGIN{FS=OFS="\t"}{print $6,"hg38_rmsk","exon",$7+1,$8,$3,$10,".","gene_id \""$11"\"; transcript_id \""$11"\"; unique_id \""$11"_"$6"_"$7+1"_"$8"_"$10"\";"    }' > hg38_UCSC_RepeatMasker_Unique.gtf`
the gtf file looks like:
| Chromosome | Source    | Feature | Start  | End   | Score | Strand | Frame | Attributes                                                                                     |
|------------|-----------|---------|--------|-------|-------|--------|-------|-------------------------------------------------------------------------------------------------|
| chr1       | hg38_rmsk | exon    | 10001  | 10468 | 13    | +      | .     | gene_id "(TAACCC)n"; transcript_id "(TAACCC)n"; unique_id "(TAACCC)n_chr1_10001_10468_+";     |
| chr1       | hg38_rmsk | exon    | 10469  | 11447 | 114   | -      | .     | gene_id "TAR1"; transcript_id "TAR1"; unique_id "TAR1_chr1_10469_11447_-";                    |
| chr1       | hg38_rmsk | exon    | 11505  | 11675 | 251   | -      | .     | gene_id "L1MC5a"; transcript_id "L1MC5a"; unique_id "L1MC5a_chr1_11505_11675_-";              |
| chr1       | hg38_rmsk | exon    | 11678  | 11780 | 294   | -      | .     | gene_id "MER5B"; transcript_id "MER5B"; unique_id "MER5B_chr1_11678_11780_-";                 |
| chr1       | hg38_rmsk | exon    | 15265  | 15355 | 230   | -      | .     | gene_id "MIR3"; transcript_id "MIR3"; unique_id "MIR3_chr1_15265_15355_-";                    |

This is the `RepeatMaskerUnique` gtf file used in our pipeline. Hope this helps!
Best regards,
Xiufeng

**Comment by Bathroomboss** [comment]
Thanks!
